[tool.poetry]
name = "melougoeslive"
version = "0.1.0"
description = ""
authors = ["Deko <gadse.deko@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"
loguru = "^0.6.0"
black = "^23.1.0"
isort = "^5.12.0"
pytest = "^7.2.2"
requests-mock = "^1.10.0"
pytest-coverage = "^0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80
